### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by mhwlng** [expired6978/CUEORGBPlugin#19]
2022-12-10 08:45:24.758 W cue.plugin.host: Signature verification failed: "C:/Program Files/Corsair/CORSAIR iCUE 4 Software/plugins/OpenRGB/CUEORGBPlugin.dll"

I installed dsound.dll (16-06-2021 20:25) 
C:\Program Files\Corsair\CORSAIR iCUE 4 Software\dsound.dll

Icue 4.31.168

**Comment by germtuna** [comment]
Looks like the winverifytrust workaround the author put in last year no longer works. Going to assume something changed on the Corsair side. Validated that globally disabling the signature check via debug mode in config.cuecfg file did not alter the outcome.
