### ISSUE TITLE
Can't compile CUEORGBPlugin

### ISSUE THREAD

**Issue by aaronspark777** [expired6978/CUEORGBPlugin#3]
Getting an error when trying to compile CUEORGBPlugin

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'unistd.h': No such file or directory	CUEORGBPlugin	D:\Downloads\CUEORGBPlugin-master\CUEORGBPlugin-master\thirdparty\OpenRGB\net_port\net_port.h	19

**Comment by expired6978** [comment]
Try the latest
