### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by CashMoney1974** [expired6978/CUEORGBPlugin#5]
Finding this entry in the iCue log and the plugin never connects to Openrgb 0.6.

"2021-06-16 17:48:13.126 W cue.plugin.host: Signature verification failed: "C:/Program Files/Corsair/CORSAIR iCUE 4 Software/plugins/OpenRGB/CUEORGBPlugin.dll"

I've tried changing the port in Openrgb and the settings.json for the plugin but no difference, always get the error above and it doesn't connect.

OpenRGB 0.6
iCue v. 4.12.214

TIA

**Comment by expired6978** [comment]
iCUE updated their plugin loading code so the signature no longer works, I've changed the dsound wrapper to be more robust by just bypassing the core function they use to verify plugins.

**Comment by CashMoney1974** [comment]
Working again, thank you!
